version: '3.9'

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8081:8080"  # Change the host port to 8081
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
